---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - 'vars/certbot-vars.yml'
    - ["vars/nginx-{{ protocol }}-vars.yml"]
    - 'vars/postgres-vars.yml'
    - 'vars/nodejs-vars.yml'
    - 'vars/redis-vars.yml'

  roles:
   - user
   - { role: ansible-role-certbot, when: protocol == "https" }
   - nginx
   - nodesource.node
   - ansible-redis
   - postgresql
   - api

  