---
postgresql_version: 9.6
# List of databases to be created (optional)
postgresql_databases:
  - name: "{{ db_name }}"

postgresql_ext_postgis_version: "2.3"
postgresql_ext_install_postgis: yes

postgresql_users:
  - name: "{{ db_user }}"
    pass: "{{ db_password }}"
    encrypted: no       # denotes if the password is already encrypted.

postgresql_database_extensions:
  - db: "{{ db_name }}"
    extensions:
    - postgis